info:
  contact: {}
paths:
  /builtin-metric-filters:
    get:
      consumes:
      - application/json
      description: 从系统中获取内置的度量过滤器信息
      produces:
      - application/json
      responses: {}
      summary: 获取内置度量过滤器
      tags:
      - 内置度量过滤器管理
swagger: "2.0"
