definitions:
  center_router.CallbackOutput:
    properties:
      access_token:
        type: string
      redirect:
        type: string
      refresh_token:
        type: string
      user:
        $ref: '#/definitions/models.User'
    type: object
  models.BusiGroupRes:
    properties:
      id:
        type: integer
      name:
        type: string
    type: object
  models.User:
    properties:
      admin:
        description: 是否为管理员(方便前端使用)
        type: boolean
      belong:
        description: 归属信息
        type: string
      busi_groups:
        description: 业务组资源
        items:
          $ref: '#/definitions/models.BusiGroupRes'
        type: array
      contacts:
        description: |-
          联系方式（内容为 map[string]string 结构）
          注意：这里我们明确指定其类型为 json.RawMessage，以便 swag 能正确识别。
          @param Contacts.body.json.type json.RawMessage
        items:
          type: integer
        type: array
      create_at:
        description: |-
          创建时间戳
          swagger:strfmt int64
        type: integer
      create_by:
        description: 创建者
        type: string
      email:
        description: 邮箱
        type: string
      id:
        description: |-
          用户ID
          swagger:strfmt int64
        type: integer
      last_active_time:
        description: 最后活跃时间戳
        type: integer
      maintainer:
        description: 是否给管理员发消息（0:not send 1:send）
        type: integer
      nickname:
        description: 昵称
        type: string
      phone:
        description: 手机号码
        type: string
      portrait:
        description: 头像URL
        type: string
      roles:
        description: 角色列表(用于与前端交互)
        items:
          type: string
        type: array
      update_at:
        description: |-
          更新时间戳
          swagger:strfmt int64
        type: integer
      update_by:
        description: 更新者
        type: string
      user_groups:
        description: 用户组资源
        items:
          $ref: '#/definitions/models.UserGroupRes'
        type: array
      username:
        description: 用户名
        type: string
    type: object
  models.UserGroupRes:
    properties:
      id:
        type: integer
      name:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/n9e/auth/callback/oauth:
    get:
      description: 获取JSON
      parameters:
      - description: id
        in: path
        name: id
        type: string
      responses:
        "200":
          description: '{"code": 200, "data": [...]}'
          schema:
            $ref: '#/definitions/center_router.CallbackOutput'
      security:
      - Bearer: []
      summary: 登录回调
      tags:
      - 菜单
  /builtin-metric-filters:
    get:
      consumes:
      - application/json
      description: 从系统中获取内置的度量过滤器信息
      produces:
      - application/json
      responses: {}
      summary: 获取内置度量过滤器
      tags:
      - 内置度量过滤器管理
swagger: "2.0"
